### ISSUE TITLE
Design request if possible

### ISSUE THREAD

**Issue by mahanthathreyee** [RocktimSaikia/hackernews-redesign#1]
Hi @RocktimSaikia, 
The site looks neat and minimal, nice work. I really like the design. 

This is what I thought could be improved, the position of the items in a row.
For example 
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/26182655/89124131-2a97ff80-d4f2-11ea-8de7-154c6f1c3b48.png">
In this row, I get headline right off the bat which is epic, but to get the author/site/... and other meta information, I have to look till the end of the row. This might be fine for first few rows but when you start going to the mid of the table you start track which row you are trying to view the information for.

This the solution I thought of
<img width="642" alt="image" src="https://user-images.githubusercontent.com/26182655/89124783-46ea6b00-d4f7-11ea-9c33-80092588b774.png">
if you notice has all the information contained in one place, the end user doesn't have the burden to go through the whole row to get relevant pieces of information.
This is old reddit post format
<img width="914" alt="image" src="https://user-images.githubusercontent.com/26182655/89124763-1e627100-d4f7-11ea-8796-c9837c306253.png">

I am interested in contributing on this, if you feel this is an valid feature

Anyways, nice redesign and keep up the effort 👍

**Comment by rocktimsaikia** [comment]
@mahanthathreyee Hi. sorry for the late response. I was busy with my internship .It just finished a month ago.
And regrading the design,Sure you can design and contribute. I will review after you make a pull request

[ps: This project was one of my first react projects, literally half a year ago when I first started learning React.]
